name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      id: buildMaven
      continue-on-error: true
      run: |
        mvn -B package --file pom.xml

    - name: Parse test results
      id: parse
      run: |
        {
          echo 'TESTS_OUTPUT<<EOF'
          cat target/surefire-reports/*.txt
          echo EOF
        } >> "$GITHUB_OUTPUT"

    - name: send telegram message on push
      if: ${{steps.buildMaven.outcome == 'success'}}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: все ок

    - name: send telegram message on failure
      if: ${{steps.buildMaven.outcome == 'failure'}}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ steps.parse.outputs.TESTS_OUTPUT }}

    - name: fail on tests failure
      if: ${{steps.buildMaven.outcome == 'failure'}}
      run: exit 1
